[package]
name = "shadermagic"
version = "0.1.1"
edition = "2021"
description = "Pseudo-glsl to msl and glsl transpiler."
license = "MIT OR Apache-2.0"

[dependencies]
miniquad = "0.4.0-alpha"

#[patch.crates-io]
#miniquad = {path = "../miniquad"}
